### ISSUE TITLE
npm run-script build error

### ISSUE THREAD

**Issue by KevTN5656** [Qendolin/pokecord-bot#31]
When I try to npm-run build error it comes up with this error 
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\KevTN\package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\KevTN\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\KevTN\AppData\Roaming\npm-cache\_logs\2020-04-22T04_03_31_448Z-
debug.log
[2020-04-22T04_03_31_448Z-debug.log](https://github.com/Qendolin/pokecord-bot/files/4513733/2020-04-22T04_03_31_448Z-debug.log)
I tried just running the build.bat and continue the setup and I loaded the extension but no direction shows in the inspect element console while on discord

**Comment by Qendolin** [comment]
please try running `npm install` and then `npm run-script build` and see it that fixes the error

**Comment by KevTN5656** [comment]
I have tried to run `npm install` then `npm run-script build` and it gave me this following error
`npm WARN saveError ENOENT: no such file or directory, open 'C:\Users\KevTN\package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\KevTN\package.json'
npm WARN KevTN No description
npm WARN KevTN No repository field.
npm WARN KevTN No README data
npm WARN KevTN No license field.

up to date in 0.645s
found 0 vulnerabilities`

**Comment by Qendolin** [comment]
You have to make sure that you are executing the commands in the folder that contains the `package.json`. Open the explorer (⊞+ E), navigate to the folder containing the `package.json` (where you extracted the .zip into or cloned into), then hold shift and right-click. Then select `Open Powershell here` or `Open command prompt here` (depending on your Windows version). Now you are ready to go execute `npm install` and `npm run-script build`

**Comment by KevTN5656** [comment]
I followed your following steps and got these errors . Sorry for all the complications :(

PS C:\Users\KevTN\Downloads\pokecord-bot-master> npm install
Program 'npm' failed to run: No application is associated with the specified file for this operationAt line:1 char:1
+ npm install
+ ~~~~~~~~~~~.
At line:1 char:1
+ npm install
+ ~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

PS C:\Users\KevTN\Downloads\pokecord-bot-master> npm run-script build
Program 'npm' failed to run: No application is associated with the specified file for this operationAt line:1 char:1
+ npm run-script build
+ ~~~~~~~~~~~~~~~~~~~~.
At line:1 char:1
+ npm run-script build
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed

**Comment by Qendolin** [comment]
It seems that you don't have npm installed correctly. Either add it to your PATH environment variable or install it correctly. Or try these commands: 
`cd C:\Users\KevTN\Downloads\pokecord-bot-master`
`& "C:\Users\KevTN\npm" install`
`& "C:\Users\KevTN\npm" run-script build`

**Comment by KevTN5656** [comment]
So I think I've sucessfully run `npm install` and `npm run-script build` but when I run npm install it says 

npm WARN discord.js@11.5.1 requires a peer of @discordjs/uws@^10.149.0 but none is installed. You must install peer dependencies yourself.

audited 1538 packages in 1.872s
found 4 vulnerabilities (1 low, 1 moderate, 2 high)
  run `npm audit fix` to fix them, or `npm audit` for details

so I run `npm audit`

  Moderate        Tmp files readable by other users

  Package         sync-exec

  Patched in      No patch available

  Dependency of   cost-of-modules

  Path            cost-of-modules > sync-exec

  More info       https://npmjs.com/advisories/310


  Low             Prototype Pollution

  Package         lodash

  Patched in      >=4.17.5

  Dependency of   cost-of-modules

  Path            cost-of-modules > cli-table2 > lodash

  More info       https://npmjs.com/advisories/577


  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.11

  Dependency of   cost-of-modules

  Path            cost-of-modules > cli-table2 > lodash

  More info       https://npmjs.com/advisories/782


  High            Prototype Pollution

  Package         lodash

  Patched in      >=4.17.12

  Dependency of   cost-of-modules

  Path            cost-of-modules > cli-table2 > lodash

  More info       https://npmjs.com/advisories/1065

found 4 vulnerabilities (1 low, 1 moderate, 2 high) in 1538 scanned packages
  4 vulnerabilities require manual review. See the full report for details.

I run `npm audit fix` returns

fixed 0 of 4 vulnerabilities in 1538 scanned packages
  4 vulnerabilities required manual review and could not be updated

So I just continued and I in fact did get PCB Client ready to show but it shows not further directions 
[https://i.imgur.com/pOkK961.png](url)

**Comment by Qendolin** [comment]
Ok, I've just merged a fix. You can pull (or redownload the zip) from the master branch. You need to run `npm run-script build` again

**Comment by KevTN5656** [comment]
Everything is working fine now. Thank you for the support
